### ISSUE TITLE
Yo, dawg, I heard you like Test Kitchen...

### ISSUE THREAD

**Issue by hartmantis** [test-kitchen/kitchen-rackspace#14]
If we did a very simple run during builds, it would catch issues like #13.

**Comment by martinb3** [comment]
It seems like this might be able to be closed, given what I'm seeing at https://travis-ci.org/test-kitchen/kitchen-rackspace.

**Comment by mburns** [comment]
+1 to this issue being resolved.

**Comment by RoboticCheese** [comment]
The Travis builds still only do style and unit checks. The idea was to actually converge a server or two in Rackspace for a full end-to-end test. That said, as an ex-employee who now has to pay full-price for his clouds, I'm somewhat less inclined to tackle that. The occasional build failure doesn't pair well with being the person who always forgets to clear orphaned servers out of his account.

**Comment by martinb3** [comment]
@RoboticCheese I'm sure I could figure out a way to get an account for this.
